#!/bin/bash
# description: Description comes here....

# Source function library.
. /etc/init.d/functions

start() {
   LOGFILE=/tmp/SnortRuleGenerator
   date >> LOGFILE
   /usr/local/bin/SnortRuleGenerator.py 2>&1 >> LOGFILE &
}

stop() {
    pkill SnortRuleGenerator
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       /usr/local/bin/SnortRuleGenerator
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0